### PR TITLE
parent_mass -> precursor_mz and notebook re-run/update

### PR DESCRIPTION
**Pull request by florian-huber**

### CODE REVIEW

**Comment by niekdejonge** [comment]
Replacing all naming worked well for the parent mass!
I removed a few filtering steps for the spectra that needed the parent mass, for the rest your changes already fixed the change to precurser_mz.
Most of my changes are changing all the tests. They should work all now.

**Comment by niekdejonge** [comment]
Still some errors occur for python 3.7.

I think the issue is the following: 
I created new pickled files (since the output of the test functions changed).
These pickled files were created with a new pickle protocol, which is not compatible with python 3.7.

A solution that might work is using pickle5: https://stackoverflow.com/questions/63329657/python-3-7-error-unsupported-pickle-protocol-5
But I didn't get it to pip install, so will have a look at it after lunch.

**Comment by niekdejonge** [comment]
To do:
Change tests, so only 5 scores are used instead of 9.
Change pickled version, to prevent errors with the pickled test files loading.

**Comment by florian-huber** [comment]
Sorry, missed the earlier pickle related question. That is indeed a known (and annoying) thing with pickle. Updating to pickle 5 would be best if that's possible so that we don't have to drop Python 3.7 testing.
(many people still run 3.7)

Let me know if we should do a session to go over it together.

**Comment by niekdejonge** [comment]
@florian-huber So the problem now is that python 3.7 is not able to load in the pickled pandas files. A solution I found is installing the pickle5 package. However the problem is, this package is not compatible with python 3.8... So if I would use this, the problem with python 3.7 is solved, but python 3.8 won't work anymore...

To solve this I was thinking that there might be a way to have different dependencies for different python versions. But I am not sure if that is possible. Do you maybe know that? So to further clarify: when installing MS2Query on python 3.7 pickle5 will be installed and used and when installing on python 3.8 normal pickle will be used.

Otherwise I will just do the easy fix: Load in the stored pickle files in version 3.8 and restore them while forcing an older serialization protocol.

**Comment by florian-huber** [comment]
I will check. Hope #124 will do exactly that.

**Comment by niekdejonge** [comment]
#124 Did the trick indeed! The errors that were still occurring in the tests, were due to the fact that we went from 9 features to 5 for the RF. For this PR I will just keep it at 9 so the tests still work, but I made an issue #125 to still change this, once we are 100% sure which features we will keep.

**Pull request merged**
